# fly.toml app configuration file generated for check-in-lah-server on 2023-11-11T23:30:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "check-in-lah-server"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"